lint-markdown: Fix stack call size exceeded
`make lint` started failing on my laptop with this error:

```
% make lint
./scripts/lint.sh
node:internal/fs/utils:534
function getStatsFromBinding(stats, offset = 0) {
                            ^

RangeError: Maximum call stack size exceeded
    at getStatsFromBinding (node:internal/fs/utils:534:29)
    at Object.statSync (node:fs:1620:10)
    at searchForMarkdown (/Users/abg/src/pulumi/hugo/scripts/lint/lint-markdown.js:85:28)
    at searchForMarkdown (/Users/abg/src/pulumi/hugo/scripts/lint/lint-markdown.js:153:16)
    at searchForMarkdown (/Users/abg/src/pulumi/hugo/scripts/lint/lint-markdown.js:153:16)
    at searchForMarkdown (/Users/abg/src/pulumi/hugo/scripts/lint/lint-markdown.js:106:16)
    at searchForMarkdown (/Users/abg/src/pulumi/hugo/scripts/lint/lint-markdown.js:153:16)
    at searchForMarkdown (/Users/abg/src/pulumi/hugo/scripts/lint/lint-markdown.js:153:16)
    at searchForMarkdown (/Users/abg/src/pulumi/hugo/scripts/lint/lint-markdown.js:153:16)
    at searchForMarkdown (/Users/abg/src/pulumi/hugo/scripts/lint/lint-markdown.js:153:16)

Node.js v19.8.1
make: *** [lint] Error 1
```

searchForMarkdown is recursive so at some point we hit the limit.
This changes searchForMarkdown to be iterative instead of recursive
so that we're not exceeding the call stack depth.

With this change, the above passes again:

```
% make lint
./scripts/lint.sh

Markdown Lint Results:
    - 938 files parsed.
    - 0 errors found.

yarn run v1.22.19
$ /Users/abg/src/pulumi/hugo/node_modules/.bin/prettier --check .
Checking formatting...
All matched files use Prettier code style!
✨  Done in 2.50s.
```